/**
 * ALAYA INSIDER — AI Agent Registry
 * Central registry of all agents with their configurations.
 */

import { AgentType, AgentConfig } from '../types';

export const AGENT_REGISTRY: Record<AgentType, AgentConfig> = {
  CONTENT_ARCHITECT: {
    type: 'CONTENT_ARCHITECT',
    name: 'Content Architect',
    description: 'Generates high-quality editorial content, guides, comparisons, and clusters.',
    capabilities: ['long_form', 'structured_output', 'internal_linking', 'schema'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 4000,
    temperature: 0.7,
    systemPrompt: 'You are the Content Architect for ALAYA INSIDER. Write with warmth, elegance, precision, and deep editorial care. Never generic. Always specific and human.',
    rateLimitPerMinute: 20,
    costPer1kTokens: 0.015,
  },
  SEO_STRATEGIST: {
    type: 'SEO_STRATEGIST',
    name: 'SEO Strategist',
    description: 'Optimizes for search, entities, schema, and AI overviews.',
    capabilities: ['keyword_research', 'entity_seo', 'schema', 'meta', 'internal_links'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 2000,
    temperature: 0.4,
    systemPrompt: 'You are an elite SEO strategist. Focus on entity understanding, helpful content, and sustainable rankings.',
    rateLimitPerMinute: 30,
    costPer1kTokens: 0.015,
  },
  TREND_RADAR: {
    type: 'TREND_RADAR',
    name: 'Trend Radar',
    description: 'Surfaces emerging trends across products, search, content, and affiliate.',
    capabilities: ['trend_detection', 'opportunity_analysis'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1500,
    temperature: 0.6,
    systemPrompt: 'You have exceptional taste and pattern recognition. Surface real, actionable trends with data-backed reasoning.',
    rateLimitPerMinute: 15,
    costPer1kTokens: 0.015,
  },
  FAQ_GENERATOR: {
    type: 'FAQ_GENERATOR',
    name: 'FAQ Generator',
    description: 'Creates helpful, schema-ready, on-brand FAQs.',
    capabilities: ['structured_output', 'schema'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1800,
    temperature: 0.5,
    systemPrompt: 'Write natural, genuinely useful FAQs that anticipate real reader questions.',
    rateLimitPerMinute: 25,
    costPer1kTokens: 0.015,
  },
  BRAND_VOICE_GUARDIAN: {
    type: 'BRAND_VOICE_GUARDIAN',
    name: 'Brand Voice Guardian',
    description: 'Reviews and refines content to match ALAYA\'s warm, elegant, intentional voice.',
    capabilities: ['tone_analysis', 'rewriting'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 2500,
    temperature: 0.6,
    systemPrompt: 'You are the guardian of ALAYA\'s voice: warm, sophisticated, never pretentious, always thoughtful.',
    rateLimitPerMinute: 20,
    costPer1kTokens: 0.015,
  },
  KNOWLEDGE_GRAPH_AI: {
    type: 'KNOWLEDGE_GRAPH_AI',
    name: 'Knowledge Graph AI',
    description: 'Builds and enriches entity relationships across the platform.',
    capabilities: ['entity_extraction', 'relationship_mapping'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 2000,
    temperature: 0.4,
    systemPrompt: 'You are a precise knowledge graph engineer.',
    rateLimitPerMinute: 15,
    costPer1kTokens: 0.015,
  },
  COMPARISON_GENERATOR: {
    type: 'COMPARISON_GENERATOR',
    name: 'Comparison Generator',
    description: 'Creates structured product/article comparisons.',
    capabilities: ['structured_output'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 2500,
    temperature: 0.5,
    systemPrompt: 'Create balanced, insightful comparisons.',
    rateLimitPerMinute: 20,
    costPer1kTokens: 0.015,
  },
  INTERNAL_LINK_ASSISTANT: {
    type: 'INTERNAL_LINK_ASSISTANT',
    name: 'Internal Link Assistant',
    description: 'Suggests relevant internal links.',
    capabilities: ['linking'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1500,
    temperature: 0.3,
    systemPrompt: 'Suggest precise internal links.',
    rateLimitPerMinute: 30,
    costPer1kTokens: 0.015,
  },
  OPPORTUNITY_FINDER: {
    type: 'OPPORTUNITY_FINDER',
    name: 'Opportunity Finder',
    description: 'Finds content and product opportunities.',
    capabilities: ['analysis'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1800,
    temperature: 0.6,
    systemPrompt: 'Identify high-value opportunities.',
    rateLimitPerMinute: 15,
    costPer1kTokens: 0.015,
  },
  SCHEMA_BUILDER: {
    type: 'SCHEMA_BUILDER',
    name: 'Schema Builder',
    description: 'Generates structured data and schema markup.',
    capabilities: ['schema'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1200,
    temperature: 0.2,
    systemPrompt: 'Output valid JSON-LD and schema.',
    rateLimitPerMinute: 25,
    costPer1kTokens: 0.015,
  },
  REVIEW_GENERATOR: {
    type: 'REVIEW_GENERATOR',
    name: 'Review Generator',
    description: 'Creates authentic-sounding reviews and summaries.',
    capabilities: ['structured_output'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1600,
    temperature: 0.7,
    systemPrompt: 'Write balanced, helpful review content.',
    rateLimitPerMinute: 20,
    costPer1kTokens: 0.015,
  },
  METADATA_GENERATOR: {
    type: 'METADATA_GENERATOR',
    name: 'Metadata Generator',
    description: 'Creates SEO titles, descriptions, keywords.',
    capabilities: ['meta'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 800,
    temperature: 0.4,
    systemPrompt: 'Generate concise, compelling metadata.',
    rateLimitPerMinute: 40,
    costPer1kTokens: 0.015,
  },
  SEMANTIC_KEYWORD: {
    type: 'SEMANTIC_KEYWORD',
    name: 'Semantic Keyword',
    description: 'Extracts and clusters semantic keywords.',
    capabilities: ['keywords'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1000,
    temperature: 0.5,
    systemPrompt: 'Surface precise semantic keywords.',
    rateLimitPerMinute: 30,
    costPer1kTokens: 0.015,
  },
  IMAGE_ALT: {
    type: 'IMAGE_ALT',
    name: 'Image Alt',
    description: 'Generates descriptive alt text.',
    capabilities: ['accessibility'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 300,
    temperature: 0.3,
    systemPrompt: 'Write descriptive, SEO-friendly alt text.',
    rateLimitPerMinute: 50,
    costPer1kTokens: 0.015,
  },
  CONTENT_REFRESH: {
    type: 'CONTENT_REFRESH',
    name: 'Content Refresh',
    description: 'Refreshes and updates existing content.',
    capabilities: ['refresh'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 3000,
    temperature: 0.6,
    systemPrompt: 'Refresh content while preserving voice.',
    rateLimitPerMinute: 15,
    costPer1kTokens: 0.015,
  },
  LINK_AUDITOR: {
    type: 'LINK_AUDITOR',
    name: 'Link Auditor',
    description: 'Audits affiliate and internal links.',
    capabilities: ['audit'],
    defaultProvider: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-20241022',
    maxTokens: 1200,
    temperature: 0.3,
    systemPrompt: 'Audit links for health and relevance.',
    rateLimitPerMinute: 25,
    costPer1kTokens: 0.015,
  },
};

export function getAgentConfig(type: AgentType): AgentConfig {
  return AGENT_REGISTRY[type];
}

export function listAgents(): AgentConfig[] {
  return Object.values(AGENT_REGISTRY);
}
